In [2]:
import pandas as pd
import numpy as np
from dateutil.parser import parse
from collections import Counter

In [3]:
df = pd.Series([10,20,30,40,50])
df

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
df = pd.Series([10,20,30,40,50])
print(list(df))

[10, 20, 30, 40, 50]


In [5]:
df = pd.Series([2, 4, 6, 8, 10])
df1 = pd.Series([1, 3, 5, 7, 9])
print("addition",df+df1)
print("substract",df-df1)
print("multiply",df*df1)
print("divide",df/df1)

addition 0     3
1     7
2    11
3    15
4    19
dtype: int64
substract 0    1
1    1
2    1
3    1
4    1
dtype: int64
multiply 0     2
1    12
2    30
3    56
4    90
dtype: int64
divide 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [6]:
print(df>df1)

0    True
1    True
2    True
3    True
4    True
dtype: bool


In [7]:
dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
df = pd.DataFrame(dict.items(),index = dict.keys())
df

0    1
a  a  100
b  b  200
c  c  300
d  d  400
e  e  800

In [8]:
arr = np.array([10,20,30,40,50])
df = pd.Series(arr)
df

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [9]:
df = pd.Series([100,200,'python',300,400])
df1 = pd.to_numeric(df,errors='coerce')
df1

0    100.0
1    200.0
2      NaN
3    300.0
4    400.0
dtype: float64

In [10]:
df = pd.DataFrame([[1,4,7],[2,5,5],[3,6,8],[4,9,12],[7,5,1],[11,0,11]])
print(df)
s = df[0]
print("1st column as a Series:\n",s)

    0  1   2
0   1  4   7
1   2  5   5
2   3  6   8
3   4  9  12
4   7  5   1
5  11  0  11
1st column as a Series:
 0     1
1     2
2     3
3     4
4     7
5    11
Name: 0, dtype: int64


In [11]:
df = pd.Series([100,200,'python',300.12,400])
print(df)
arr = np.array(df)
arr

0       100
1       200
2    python
3    300.12
4       400
dtype: object


array([100, 200, 'python', 300.12, 400], dtype=object)

In [12]:
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])
print(s)
s1 = s.apply(pd.Series).stack().reset_index(drop=True)
print(s1)

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [13]:
s = pd.Series(['100','200','python','300.12','400'])
print(s)
s.sort_values()

0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
3    300.12
4       400
2    python
dtype: object

In [14]:
s = pd.Series(['100','200','python','300.12','400'])
s1 = pd.Series(['500','php'])
pd.concat([s,s1]).reset_index(drop=True)

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

In [15]:
s = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
s1= s[s<6]
s1

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [16]:
df =pd.Series({'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5})
df = df.reindex(index = ['B','A','C','D','E'])
df

B    2
A    1
C    3
D    4
E    5
dtype: int64

In [17]:
s = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
print("mean : ",s.mean())
print("standart deviation : ",s.std())

mean :  4.818181818181818
standart deviation :  2.522624895547565


In [18]:
s1 = pd.Series([1,2,3,4,5])
print(s1)
s2 = pd.Series([2,4,6,8,10])
print(s2)
s = s1[~s1.isin(s2)]
s

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64


0    1
2    3
4    5
dtype: int64

In [19]:
s1 = pd.Series([1,2,3,4,5])
print(s1)
s2 = pd.Series([2,4,6,8,10])
print(s2)
s = pd.concat([s1,s2],join='outer').drop_duplicates()[~s1.isin(s2)]
s

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64


0     1
2     3
4     5
2     6
4    10
dtype: int64

In [20]:
s1 = pd.Series([1,2,3,4,5])
print(s1.min())
print(np.percentile(df,[25,50,75]))

1
[2. 3. 4.]


In [21]:
s1 = pd.Series([1,2,3,4,1,5,1,5,1,2,4,4,2,1,2])
s1.value_counts()

1    5
2    4
4    3
5    2
3    1
Name: count, dtype: int64

In [22]:
result = s1[~s1.isin(s1.value_counts().index[0:1])]='other'
s1

C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_20976\1526193720.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'other' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result = s1[~s1.isin(s1.value_counts().index[0:1])]='other'


0         1
1     other
2     other
3     other
4         1
5     other
6         1
7     other
8         1
9     other
10    other
11    other
12    other
13        1
14    other
dtype: object

In [23]:
s1 = pd.Series([1,9,8,6,9,7,1,1,1])
print(s1)
np.where(s1%5==0)

0    1
1    9
2    8
3    6
4    9
5    7
6    1
7    1
8    1
dtype: int64


(array([], dtype=int64),)

In [24]:
s1 = pd.Series([1,2,3,4,1,5,1,5,1,2,4,4,2,1,2])
arr = np.array([1,3,4,6,7,11])
s1[arr]

1     2
3     4
4     1
6     1
7     5
11    4
dtype: int64

In [25]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s1)
arr = pd.Series([1,3,5,7,10])
print(arr)
[pd.Index(s1).get_loc(i) for i in arr]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0     1
1     3
2     5
3     7
4    10
dtype: int64


[0, 2, 4, 6, 9]

In [26]:
s1 = pd.Series(['php','python','java','c#'])
s1.map(lambda x: x[0].upper()+x[1:-1]+x[-1].upper())

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

In [27]:
s1.map(lambda x: len(x))

0    3
1    6
2    4
3    2
dtype: int64

In [28]:
s1 = pd.Series([1,3,5,8,10,11,15])
print(s1)
print(s1.diff().tolist())
print(s1.diff().diff().tolist())

0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


In [29]:
s1 = pd.Series(['01 Jan 2015', '10-02-2016' , '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
print(s1)
s2 = pd.to_datetime(s1,format = 'mixed')
s2

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object


0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [30]:
print('Day of month:',s2.dt.day.tolist())
print('Day of year:',s2.dt.dayofyear.tolist())
arr = ['01 Jan 2015', '10-02-2016' , '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20']
print('Week number:',list(map(lambda x: pd.Period(x,freq = 'D').weekofyear,arr)))
print('Day of week:',s2.dt.day_name().tolist())

Day of month: [1, 2, 7, 6, 12, 6]
Day of year: [1, 276, 66, 126, 103, 96]
Week number: [1, 39, 10, 19, 15, 14]
Day of week: ['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


In [31]:
s1 = pd.Series(['Jan 2015', 'Feb 2016' , 'Mar 2017', 'Apr 2018', 'May 2019'])
print(s1)
n=11
s1 = pd.Series(map(lambda d : '11 '+d,s1))
s2 = pd.to_datetime(s1,format = 'mixed')
s2

0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object


0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]

In [32]:
s1 = pd.Series(['Red', 'Green' , 'Orange', 'Pink', 'Yellow', 'White'])
print(s1)
s1[s1.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)]

0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object


1     Green
2    Orange
4    Yellow
5     White
dtype: object

In [33]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([11,8,7,5,6,5,3,4,7,1])
print(np.linalg.norm(s1-s2))

16.492422502470642


In [34]:
s1 = pd.Series([1,8,7,5,6,5,3,4,7,1])
(np.where(np.diff(np.sign(np.diff(s1)))==-2)[0]+1)

array([1, 4, 8], dtype=int64)

In [43]:
s1=pd.Series(list("abc def abcdef icd"))
"".join(s1.replace(' ',s1.value_counts().index[-1]))

'abcidefiabcdefiicd'

In [36]:
s = pd.Series(np.random.randn(14)*10)
[s.autocorr(i).round(2) for i in range(11)]

[1.0, 0.25, -0.12, 0.2, 0.07, 0.14, 0.15, 0.31, 0.44, 0.23, -0.56]

In [37]:
pd.Series(pd.date_range('2020-01-05','2020-12-31',freq = 'W-SUN'))

0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]

In [38]:
s1 = pd.Series([0,1,2,3,4],index =('A','B','C','D','E') )
pd.DataFrame(s1).reset_index()

index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4

In [39]:
s1 = pd.Series([0,1,2,3,4,5,6,7,8,9])
print(s1)
s2 = pd.Series(['p', 'q' , 'r', 's', 't', 'u','v', 'w' , 'x', 'y'])
print(s2)
pd.concat((s1,s2),axis=1)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object


0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y

In [40]:
s1 = pd.Series([0,1,2,3,4,5,6,7,8,9])
print(s1)
s2 = pd.Series([0,1,2,3,4,5,6,7,8,9])
print(s2)
s1==s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

In [41]:
s1 = pd.Series([1,3,7,5,9,4,9,1,9,0])
print(s1)
print(s1.idxmin())
print(s1.idxmax())

0    1
1    3
2    7
3    5
4    9
5    4
6    9
7    1
8    9
9    0
dtype: int64
9
4


In [42]:
s1 = pd.DataFrame([[68.0,78.0,84,86],[75.0,75.0,94,97],[86.0,np.NaN,89,96],[80.0,80.0,86,72],[np.NaN,86.0,86,83]], columns=('W','X','Y','Z'))
s2 = pd.Series([68.0,75.0,86.0,80.0,np.NaN])
s1.ne(s2,axis=0)

W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True