### Install gensim library

In [1]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: gensim in c:\users\administrator.dai-pc2\anaconda3\lib\site-packages (4.3.0)
     ---------------------------------------- 0.0/59.0 kB ? eta -:--:--
     ---------------------------------- ----- 51.2/59.0 kB 2.7 MB/s eta 0:00:01
     ---------------------------------------- 59.0/59.0 kB 1.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
   ---------------------------------------- 0.0/60.3 kB ? eta -:--:--
   ---------------------------------------- 60.3/60.3 kB 3.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
    --------------------------------------- 0.4/14.8 MB 11.2 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/14.8 MB 8.8 MB/s eta 0:00:02
   --- -----------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 4.29.0 requires typer<1.0,>=0.12; sys_platform != "emscripten", but you have typer 0.9.4 which is incompatible.
tensorboard 2.15.1 requires protobuf<4.24,>=3.19.6, but you have protobuf 4.25.3 which is incompatible.


In [1]:
from gensim.models import Word2Vec

In [2]:
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "I like eating apples and bananas.",
    "Natural language processing is a fascinating field."
]

In [3]:
from nltk.tokenize import word_tokenize

In [4]:
final_data = []
for sent in sentences:
    final_data.append(word_tokenize(sent))

final_data

[['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog', '.'],
 ['I', 'like', 'eating', 'apples', 'and', 'bananas', '.'],
 ['Natural', 'language', 'processing', 'is', 'a', 'fascinating', 'field', '.']]

In [7]:
## Create an object
model = Word2Vec(final_data, min_count = 1, vector_size=10)

In [8]:
model.wv['apples']

array([ 0.07898068, -0.06989504, -0.09155865, -0.00355753, -0.03099841,
        0.07894317,  0.05938574, -0.01545663,  0.01510963,  0.01790041],
      dtype=float32)

In [9]:
model.wv['bananas']

array([-0.08534335,  0.03207107, -0.04637997, -0.05088955,  0.03589618,
        0.05370339,  0.07769515, -0.05766506,  0.07433361,  0.06625496],
      dtype=float32)

In [10]:
def get_embedding(word):
    try:
        word_embedding = model.wv[word]
        print(f"Word embedding for '{word} : {word_embedding}'")
    except KeyError:
        print(f"Word '{word}' not found in vocabulary.")

In [11]:
get_embedding('fox')

Word embedding for 'fox : [-0.08157917  0.04495798 -0.04137076  0.00824536  0.08498619 -0.04462177
  0.045175   -0.0678696  -0.03548489  0.09398508]'


In [12]:
get_embedding('dog')

Word embedding for 'dog : [-0.08619688  0.03665738  0.05189884  0.05741938  0.07466918 -0.06167675
  0.01105614  0.06047282 -0.0284005  -0.06173522]'


In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
cosine_similarity(model.wv['apples'].reshape(1,-1),model.wv['bananas'].reshape(1,-1))

array([[0.18977958]], dtype=float32)

In [15]:
cosine_similarity(model.wv['fox'].reshape(1,-1),model.wv['dog'].reshape(1,-1))

array([[0.2238495]], dtype=float32)

In [16]:
cosine_similarity(model.wv['apples'].reshape(1,-1),model.wv['fox'].reshape(1,-1))

array([[-0.21142587]], dtype=float32)

In [17]:
cosine_similarity(model.wv['bananas'].reshape(1,-1),model.wv['dog'].reshape(1,-1))

array([[-0.18159427]], dtype=float32)

In [18]:
import nltk
nltk.download('abc')

[nltk_data] Downloading package abc to C:\Users\Administrator.DAI-
[nltk_data]     PC2\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\abc.zip.


True

In [19]:
from nltk.corpus import abc

In [20]:
sents = abc.sents()
sents

[['PM', 'denies', 'knowledge', 'of', 'AWB', 'kickbacks', 'The', 'Prime', 'Minister', 'has', 'denied', 'he', 'knew', 'AWB', 'was', 'paying', 'kickbacks', 'to', 'Iraq', 'despite', 'writing', 'to', 'the', 'wheat', 'exporter', 'asking', 'to', 'be', 'kept', 'fully', 'informed', 'on', 'Iraq', 'wheat', 'sales', '.'], ['Letters', 'from', 'John', 'Howard', 'and', 'Deputy', 'Prime', 'Minister', 'Mark', 'Vaile', 'to', 'AWB', 'have', 'been', 'released', 'by', 'the', 'Cole', 'inquiry', 'into', 'the', 'oil', 'for', 'food', 'program', '.'], ...]

In [21]:
len(sents)

29059

In [28]:
## Create an object
model = Word2Vec(sents, min_count = 1, vector_size=10)

In [29]:
len(model.wv.key_to_index) ## no of unique words

31885

In [30]:
data = model.wv.most_similar('science')
print(data)

[('authority', 0.9829927682876587), ('capitalise', 0.9745134711265564), ('Dubbo', 0.9721439480781555), ('arousal', 0.9708213210105896), ('Hofmann', 0.9699689745903015), ('leading', 0.9698118567466736), ('nurse', 0.9649820327758789), ('Women', 0.964935302734375), ('bulk', 0.964584469795227), ('publisher', 0.9623174071311951)]


In [31]:
data = model.wv.most_similar('publisher')
print(data)

[('science', 0.9623174071311951), ('slash', 0.95766282081604), ('Dubbo', 0.9568352103233337), ('earth', 0.9567673802375793), ('tanning', 0.9550619721412659), ('eliminating', 0.954790472984314), ('Parkinson', 0.9522252678871155), ('glands', 0.9514176249504089), ('capitalise', 0.9484747648239136), ('banking', 0.9481655955314636)]


In [32]:
cosine_similarity(model.wv['science'].reshape(1,-1),
                  model.wv['publisher'].reshape(1,-1))

array([[0.9623175]], dtype=float32)